/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalpii;

import java.awt.BorderLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelado.*;
import static proyectofinalpii.PanelPrincipal.previewPanel;
import CONTROL.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author crack
 */
public class AddPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form AddLibro
     */
    public AddPrestamo() {
        initComponents();
    }
    //METODOS PERSONALIZADOS----------------------------------
    public boolean LibroCheck(LinkedList<Libro> Libros, int IdLibro){
        for (int i = 0; i < Libros.size(); i++) {
            Libro tmpObj = Libros.get(i);
            if(String.valueOf(tmpObj.getIdLibro()).equals(String.valueOf(IdLibro))){
                return true;
            }else{
                
            }
        }return false;
    }
    public boolean DisponibleCheck(LinkedList<Libro> Libros, int IdLibro){
        for (int i = 0; i < Libros.size(); i++) {
            Libro tmpObj = Libros.get(i);
            if(tmpObj.isStatus()){
                return true;
            }else{
                
            }
        }return false;

    }
    public boolean UsuarioCheck(LinkedList<Usuario> Usuarios ,int IdUsuarioIN){
        for (int i = 0; i < Usuarios.size(); i++) {
            Usuario tmpObj = Usuarios.get(i);
            if (String.valueOf(tmpObj.getIdUsuario()).equals(String.valueOf(IdUsuarioIN))) {
                return true;
            }else{

            }
        }return false;
    }
    
    public void CerrarLibro(LinkedList<Libro> Libros, int IdLibro){
        for (int i = 0; i < Libros.size(); i++) {
            Libro tmpObj = Libros.get(i);
            if(String.valueOf(tmpObj.getIdLibro()).equals(String.valueOf(IdLibro))){
                Libro Aux = Main.Storage.Libros.get(i);
                Aux.setStatus(false);
                Main.Storage.Libros.set(i, Aux);
            }else{
                
            }
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    //----------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxIdPrestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxIdLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxIdUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxFechaSalida = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxFechaEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 4, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id préstamo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jtxIdPrestamo.setText("Ingresa el ID del préstamo.");
        jtxIdPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxIdPrestamoMousePressed(evt);
            }
        });
        jtxIdPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdPrestamoActionPerformed(evt);
            }
        });
        add(jtxIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 124, 189, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id libro");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jtxIdLibro.setText("Ingrese ID del libro.");
        jtxIdLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxIdLibroMousePressed(evt);
            }
        });
        jtxIdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdLibroActionPerformed(evt);
            }
        });
        add(jtxIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 188, 189, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id usuario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jtxIdUsuario.setText("Ingrese el ID del usuario.");
        jtxIdUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxIdUsuarioMousePressed(evt);
            }
        });
        jtxIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdUsuarioActionPerformed(evt);
            }
        });
        add(jtxIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 260, 189, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de salida");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jtxFechaSalida.setText("AAAA-MM-DD");
        jtxFechaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxFechaSalidaMousePressed(evt);
            }
        });
        jtxFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxFechaSalidaActionPerformed(evt);
            }
        });
        add(jtxFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 124, 241, -1));

        jPanel1.setBackground(new java.awt.Color(35, 35, 91));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUEVO PRÉSTAMO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jtxFechaEntrada.setText("AAAA-MM-DD");
        jtxFechaEntrada.setToolTipText("");
        jtxFechaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxFechaEntradaMousePressed(evt);
            }
        });
        jtxFechaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxFechaEntradaActionPerformed(evt);
            }
        });
        add(jtxFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 241, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de entrada");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxIdPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdPrestamoActionPerformed

    private void jtxIdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdLibroActionPerformed

    private void jtxIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdUsuarioActionPerformed

    private void jtxFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxFechaSalidaActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        //SNIPPET DE CÓDIGO QUE OBTIENE LOS DATOS DE LOS INPUTS Y LOS AÑADE AL ALMACÉN.
        int IdPrestamo  = Integer.parseInt(jtxIdPrestamo.getText());
        int IdLibro = Integer.parseInt(jtxIdLibro.getText());
        int IdUsuario = Integer.parseInt(jtxIdUsuario.getText());
        int indexOfLibro =-1;
        String FechaEntrada = jtxFechaEntrada.getText();
        String FechaSalida = jtxFechaSalida.getText();
        //LLAMADA A LA VERIFICACION
        boolean flagLibro = LibroCheck(Main.Storage.Libros, IdLibro);;
        boolean flagDisponible = DisponibleCheck(Main.Storage.Libros, IdLibro);
        boolean flagUsuario = UsuarioCheck(Main.Storage.Usuarios, IdUsuario);;
        
        
        try {
            if(flagDisponible && flagLibro && flagUsuario){
                LogPrestamo newPrestamo = new LogPrestamo(IdPrestamo, IdLibro, IdUsuario, FechaEntrada, FechaSalida);
                Main.Storage.Prestamos.add(newPrestamo);
                System.out.println(Main.Storage.Prestamos.peekLast());
                CerrarLibro(Main.Storage.Libros, IdLibro);
            }
            else{
                JOptionPane.showMessageDialog(null," Verifica que los datos sean correctos");
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(AddPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        //ESTE CODIGO REGRESA A LA LISTA DE USUARIOS
        Prestamos p1 = new Prestamos();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
        //-------------------------------------------
    }//GEN-LAST:event_jPanel1MousePressed

    private void jtxFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxFechaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxFechaEntradaActionPerformed

    private void jtxIdPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxIdPrestamoMousePressed
        if(jtxIdPrestamo.getText().equals("Ingresa el ID del préstamo."))
        jtxIdPrestamo.setText("");       
    }//GEN-LAST:event_jtxIdPrestamoMousePressed

    private void jtxIdLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxIdLibroMousePressed
      if(jtxIdLibro.getText().equals("Ingrese ID del libro."))
        jtxIdLibro.setText(""); 
    }//GEN-LAST:event_jtxIdLibroMousePressed

    private void jtxIdUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxIdUsuarioMousePressed
      if(jtxIdUsuario.getText().equals("Ingrese el ID del usuario."))
        jtxIdUsuario.setText(""); 
    }//GEN-LAST:event_jtxIdUsuarioMousePressed

    private void jtxFechaSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxFechaSalidaMousePressed
      if(jtxFechaSalida.getText().equals("AAAA-MM-DD"))
        jtxFechaSalida.setText(""); 
    }//GEN-LAST:event_jtxFechaSalidaMousePressed

    private void jtxFechaEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxFechaEntradaMousePressed
      if(jtxFechaEntrada.getText().equals("AAAA-MM-DD"))
        jtxFechaEntrada.setText(""); 
    }//GEN-LAST:event_jtxFechaEntradaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxFechaEntrada;
    private javax.swing.JTextField jtxFechaSalida;
    private javax.swing.JTextField jtxIdLibro;
    private javax.swing.JTextField jtxIdPrestamo;
    private javax.swing.JTextField jtxIdUsuario;
    // End of variables declaration//GEN-END:variables


}
