
package proyectofinalpii;

import java.awt.BorderLayout;
import static proyectofinalpii.PanelPrincipal.previewPanel;
import CONTROL.*;
import modelado.*;


public class AddUser extends javax.swing.JPanel {
    
 

    /**
     * Creates new form AddLibro
     */
    public AddUser() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtApeP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtApeM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtDir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(27, 4, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jtxtNom.setText("Ingrese el nombre.");
        jtxtNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtNomMousePressed(evt);
            }
        });
        jtxtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNomActionPerformed(evt);
            }
        });
        add(jtxtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 124, 189, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jtxtApeP.setText("Ingrese el apellido paterno.");
        jtxtApeP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtApePMousePressed(evt);
            }
        });
        jtxtApeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApePActionPerformed(evt);
            }
        });
        add(jtxtApeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 188, 189, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jtxtApeM.setText("Ingrese el apellido materno.");
        jtxtApeM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtApeMMousePressed(evt);
            }
        });
        jtxtApeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApeMActionPerformed(evt);
            }
        });
        add(jtxtApeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 260, 189, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id usuario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jtxtId.setText("Ingrese ID de usuario.");
        jtxtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtIdMousePressed(evt);
            }
        });
        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 124, 190, -1));

        jPanel1.setBackground(new java.awt.Color(35, 35, 91));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUEVO USUARIO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jtxtDir.setText("Ingrese la dirección.");
        jtxtDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtDirMousePressed(evt);
            }
        });
        jtxtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDirActionPerformed(evt);
            }
        });
        add(jtxtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 190, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de usuario");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Normal" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNomActionPerformed

    private void jtxtApePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApePActionPerformed

    private void jtxtApeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApeMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApeMActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //SNIPPET DE CÓDIGO QUE OBTIENE LOS DATOS DE LOS INPUTS Y LOS AÑADE AL ALMACÉN.
        String Nombre = jtxtNom.getText();
        String ApellidoP = jtxtApeP.getText();
        String ApellidoM = jtxtApeM.getText();
        int IdUsuario = Integer.parseInt(jtxtId.getText());
        String Direccion = jtxtDir.getText();
        int TipoUsuario = jComboBox1.getSelectedIndex();
        Usuario NewUser = new Usuario(IdUsuario,TipoUsuario,Nombre,ApellidoP,ApellidoM,Direccion);
        Main.Storage.Usuarios.add(NewUser);
        System.out.println(Main.Storage.Usuarios.peekLast());
        //------------------------------------------------------
        
        //ESTE CODIGO REGRESA A LA LISTA DE USUARIOS
        Usuarios p1 = new Usuarios();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
        //-------------------------------------------
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jtxtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDirActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jtxtNomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNomMousePressed
      if(jtxtNom.getText().equals("Ingrese el nombre."))
      jtxtNom.setText(""); 
    }//GEN-LAST:event_jtxtNomMousePressed

    private void jtxtApePMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtApePMousePressed
      if(jtxtApeP.getText().equals("Ingrese el apellido paterno."))
      jtxtApeP.setText(""); 
    }//GEN-LAST:event_jtxtApePMousePressed

    private void jtxtApeMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtApeMMousePressed
      if(jtxtApeM.getText().equals("Ingrese el apellido materno."))
      jtxtApeM.setText(""); 
    }//GEN-LAST:event_jtxtApeMMousePressed

    private void jtxtIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIdMousePressed
      if(jtxtId.getText().equals("Ingrese ID de usuario."))
      jtxtId.setText(""); 
    }//GEN-LAST:event_jtxtIdMousePressed

    private void jtxtDirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDirMousePressed
      if(jtxtDir.getText().equals("Ingrese la dirección."))
      jtxtDir.setText(""); 
    }//GEN-LAST:event_jtxtDirMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtApeM;
    private javax.swing.JTextField jtxtApeP;
    private javax.swing.JTextField jtxtDir;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtNom;
    // End of variables declaration//GEN-END:variables
}
