package proyectofinalpii;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;


/**
 *
 * @author crack
 */
public class PanelPrincipal extends javax.swing.JFrame {
   //Variables para mover la ventana principal con los eventos del panel título.
    int xMouse;
    int yMouse;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        
            //Fecha header
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        FECHA.setText(+dia+" de "+meses[month - 1]+" de "+year);
        Calendar fecha = new GregorianCalendar();
        String hora =Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
        String minutos =Integer.toString(fecha.get(Calendar.MINUTE));
        String horacomp = hora +":"+minutos;
        Jhora.setText(horacomp);
        
            // Cargar por default el panel home. 
        home p1 = new home();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
       
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
 
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLibro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPrestamo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BarraTitulo = new javax.swing.JPanel();
        titulo_barra_ = new javax.swing.JLabel();
        btnRojo = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        head_ = new javax.swing.JPanel();
        FECHA = new javax.swing.JLabel();
        Jhora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        previewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setBackground(new java.awt.Color(6, 6, 20));
        Background.setAlignmentX(0.0F);
        Background.setAlignmentY(0.0F);
        Background.setMinimumSize(new java.awt.Dimension(1020, 640));
        Background.setPreferredSize(new java.awt.Dimension(1020, 640));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1032, 347, -1, -1));

        Menu.setBackground(new java.awt.Color(15, 15, 40));
        Menu.setPreferredSize(new java.awt.Dimension(270, 431));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(35, 35, 91));
        btn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Home.setMinimumSize(new java.awt.Dimension(109, 40));
        btn_Home.setPreferredSize(new java.awt.Dimension(109, 40));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HomeMousePressed(evt);
            }
        });
        btn_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIO");
        btn_Home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 50));

        btnUser.setBackground(new java.awt.Color(26, 26, 64));
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUser.setMinimumSize(new java.awt.Dimension(109, 40));
        btnUser.setPreferredSize(new java.awt.Dimension(109, 40));
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserMousePressed(evt);
            }
        });
        btnUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIOS");
        btnUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        btnLibro.setBackground(new java.awt.Color(26, 26, 64));
        btnLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLibroMousePressed(evt);
            }
        });
        btnLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 51, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIBROS");
        btnLibro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btnLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 50));

        btnPrestamo.setBackground(new java.awt.Color(26, 26, 64));
        btnPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamoMousePressed(evt);
            }
        });
        btnPrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 51, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRÉSTAMOS");
        btnPrestamo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btnPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 50));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        BarraTitulo.setBackground(new java.awt.Color(13, 10, 23));
        BarraTitulo.setMinimumSize(new java.awt.Dimension(0, 0));
        BarraTitulo.setPreferredSize(new java.awt.Dimension(1020, 30));
        BarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraTituloMouseDragged(evt);
            }
        });
        BarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraTituloMousePressed(evt);
            }
        });
        BarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_barra_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titulo_barra_.setForeground(new java.awt.Color(255, 0, 51));
        titulo_barra_.setText("Biblioxs 0.9");
        BarraTitulo.add(titulo_barra_, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 30));

        btnRojo.setAlignmentX(0.0F);
        btnRojo.setAlignmentY(0.0F);
        btnRojo.setMinimumSize(new java.awt.Dimension(30, 30));
        btnRojo.setPreferredSize(new java.awt.Dimension(30, 30));
        btnRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRojoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRojoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRojoMousePressed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setAlignmentY(0.0F);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salir.setMaximumSize(new java.awt.Dimension(30, 30));
        salir.setMinimumSize(new java.awt.Dimension(30, 30));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnRojoLayout = new javax.swing.GroupLayout(btnRojo);
        btnRojo.setLayout(btnRojoLayout);
        btnRojoLayout.setHorizontalGroup(
            btnRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRojoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnRojoLayout.setVerticalGroup(
            btnRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRojoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BarraTitulo.add(btnRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        Background.add(BarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        BarraTitulo.getAccessibleContext().setAccessibleParent(this);

        head_.setBackground(new java.awt.Color(0, 0, 0));
        head_.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FECHA.setBackground(new java.awt.Color(27, 0, 75));
        FECHA.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        FECHA.setForeground(new java.awt.Color(102, 102, 255));
        FECHA.setText("FECHA");
        head_.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        Jhora.setBackground(new java.awt.Color(102, 102, 255));
        Jhora.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Jhora.setForeground(new java.awt.Color(102, 102, 255));
        Jhora.setText("HORA");
        head_.add(Jhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Inicio de sesión:");
        head_.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        Background.add(head_, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 150));

        previewPanel.setBackground(new java.awt.Color(68, 18, 18));
        previewPanel.setAlignmentX(0.0F);
        previewPanel.setAlignmentY(0.0F);
        previewPanel.setPreferredSize(new java.awt.Dimension(750, 430));

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        Background.add(previewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void BarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraTituloMousePressed

    private void BarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_BarraTituloMouseDragged

    private void btnRojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRojoMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnRojoMousePressed

    private void btnRojoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRojoMouseExited
        btnRojo.setBackground(new Color(255,255,255));
        salir.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_btnRojoMouseExited

    private void btnRojoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRojoMouseEntered
        btnRojo.setBackground(new Color(204,0,0));
        salir.setForeground(Color.white);
    }//GEN-LAST:event_btnRojoMouseEntered

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_salirMousePressed

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        btnRojo.setBackground(new Color(255,255,255));
        salir.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        btnRojo.setBackground(new Color(204,0,0));
        salir.setForeground(Color.white);
    }//GEN-LAST:event_salirMouseEntered

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        if(btn_Home.getBackground().getRGB() == -15574355)
            setColor(btn_Home);
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        if(btnUser.getBackground().getRGB() == -15574355)
            setColor(btnUser);
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMouseEntered
        if(btnLibro.getBackground().getRGB() == -15574355)
            setColor(btnLibro);
    }//GEN-LAST:event_btnLibroMouseEntered

    private void btnPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMouseEntered
        if(btnPrestamo.getBackground().getRGB() == -15574355)
            setColor(btnPrestamo);
    }//GEN-LAST:event_btnPrestamoMouseEntered

    private void btn_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMousePressed
        setColor(btn_Home);
        resetColor(btnUser);
        resetColor(btnLibro);
        resetColor(btnPrestamo);
        
        home p1 = new home();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
        
    
    }//GEN-LAST:event_btn_HomeMousePressed

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        if(btnUser.getBackground().getRGB() != -15574355 || btnLibro.getBackground().getRGB() != -15574355
            || btnPrestamo.getBackground().getRGB() != -15574355)
            resetColor(btn_Home);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btnUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMousePressed
        setColor(btnUser);
        resetColor(btn_Home);
        resetColor(btnLibro);
        resetColor(btnPrestamo);
        
        Usuarios p1 = new Usuarios();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();

    }//GEN-LAST:event_btnUserMousePressed

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        if(btn_Home.getBackground().getRGB() != -15574355 || btnLibro.getBackground().getRGB() != -15574355
            || btnPrestamo.getBackground().getRGB() != -15574355)
            resetColor(btnUser);
    }//GEN-LAST:event_btnUserMouseExited

    private void btnLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMousePressed
        setColor(btnLibro);
        resetColor(btn_Home);
        resetColor(btnUser);
        resetColor(btnPrestamo);
        
        Libros p1 = new Libros();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
    }//GEN-LAST:event_btnLibroMousePressed

    private void btnPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMousePressed
        setColor(btnPrestamo);
        resetColor(btn_Home);
        resetColor(btnLibro);
        resetColor(btnUser);
        
        Prestamos p1 = new Prestamos();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
    }//GEN-LAST:event_btnPrestamoMousePressed

    private void btnLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMouseExited
        if(btnUser.getBackground().getRGB() != -15574355 || btn_Home.getBackground().getRGB() != -15574355
            || btnPrestamo.getBackground().getRGB() != -15574355)
            resetColor(btnLibro);
    }//GEN-LAST:event_btnLibroMouseExited

    private void btnPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamoMouseExited
        if(btnUser.getBackground().getRGB() != -15574355 || btnLibro.getBackground().getRGB() != -15574355
            || btn_Home.getBackground().getRGB() != -15574355)
            resetColor(btnPrestamo);
    }//GEN-LAST:event_btnPrestamoMouseExited
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(35,35,91));
    }
 
    void resetColor(JPanel panel){
        panel.setBackground(new Color(26,26,64));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarraTitulo;
    private javax.swing.JLabel FECHA;
    private javax.swing.JLabel Jhora;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btnLibro;
    private javax.swing.JPanel btnPrestamo;
    private javax.swing.JPanel btnRojo;
    private javax.swing.JPanel btnUser;
    private javax.swing.JPanel btn_Home;
    private javax.swing.JPanel head_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel previewPanel;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel titulo_barra_;
    // End of variables declaration//GEN-END:variables
}
