/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalpii;

import java.awt.BorderLayout;
import static proyectofinalpii.PanelPrincipal.previewPanel;
import CONTROL.*;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import modelado.*;

/**
 *
 * @author crack
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     */
    public Prestamos() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 4, 35));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id préstamo", "Id libro", "Id usuario", "Fecha de salida", "Fecha de entrada", "Días"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 290));

        jPanel1.setBackground(new java.awt.Color(35, 35, 91));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(80, 25));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 100, 30));

        jPanel2.setBackground(new java.awt.Color(35, 35, 91));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Editar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 100, 30));

        jPanel3.setBackground(new java.awt.Color(35, 35, 91));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Borrar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 100, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Préstamos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 40));
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos() {
        String Mat[] [] = new String[Main.Storage.Prestamos.size()][6];
        LogPrestamo aux;
        for (int i = 0; i < Main.Storage.Prestamos.size(); i++) {
            aux = Main.Storage.Prestamos.get(i);
            
            Mat [i][0]= Integer.toString(aux.getIdPrestamo());
            Mat [i][1]= Integer.toString(aux.getIdUsuario());
            Mat [i][2]= Integer.toString(aux.getIdLibro());
            Mat [i][3]= aux.getFechaSalida().toString();
            Mat [i][4]= aux.getFechaEntrada().toString();;
            Mat [i][5]= Float.toString(aux.getDias());
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(Mat,new String [] {"ID Prestamo", "ID Usuario", "ID Libro", "Fecha Salida", "Fecha Entrada", "Días"}));
    }

        
        
        
        
        
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        AddPrestamo p1 = new AddPrestamo();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        int c;
        String IdUsuario,IdLibro,FechaEntrada,FechaSalida;
        long Dias;
        LogPrestamo aux;
        try {
            c = jTable1.getSelectedRow();
            aux = Main.Storage.Prestamos.get(c);
            FechaEntrada = JOptionPane.showInputDialog("Fecha de Entrada:");
            aux.setFechaEntrada(LocalDate.parse(FechaEntrada,DateTimeFormatter.ISO_LOCAL_DATE));
            aux = Main.Storage.Prestamos.get(c);
            FechaSalida = JOptionPane.showInputDialog("Fecha de Salida:");
            aux.setFechaSalida(LocalDate.parse(FechaSalida,DateTimeFormatter.ISO_LOCAL_DATE));
            Duration diff = Duration.between(aux.getFechaEntrada().atStartOfDay(), aux.getFechaSalida().atStartOfDay());
            Dias = diff.toDays();
            aux = Main.Storage.Prestamos.get(c);
            aux.setDias(Dias);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoje una fila");
        }
        cargarDatos();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        int c;
        try {
            c= jTable1.getSelectedRow();
            Main.Storage.Prestamos.remove(c);    
            Libro Aux = Main.Storage.Libros.get(c);
            Aux.setStatus(true);
            Main.Storage.Libros.set(c, Aux);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoje una fila para eliminar");
        }
        cargarDatos();
    }//GEN-LAST:event_jPanel3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
