/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalpii;

import java.awt.BorderLayout;
import static proyectofinalpii.PanelPrincipal.previewPanel;
import CONTROL.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import modelado.*;


/**
 *
 * @author crack
 */
public class Usuarios extends javax.swing.JPanel {
    /**
     * Creates new form Libros
     */
    public Usuarios() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 4, 35));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Dirección", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 290));

        jPanel1.setBackground(new java.awt.Color(35, 35, 91));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(80, 25));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 100, 30));

        jPanel2.setBackground(new java.awt.Color(35, 35, 91));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Editar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 100, 30));

        jPanel3.setBackground(new java.awt.Color(35, 35, 91));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Borrar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 100, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuarios registrados");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        AddUser p1 = new AddUser();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        cargarDatos();
        previewPanel.removeAll();
        previewPanel.add(p1, BorderLayout.CENTER);
        previewPanel.revalidate();
        previewPanel.repaint();
    }//GEN-LAST:event_jPanel1MousePressed
 public void cargarDatos() {
        String Mat[] [] = new String[Main.Storage.Usuarios.size()][6];
        Usuario aux;
        for (int i = 0; i < Main.Storage.Usuarios.size(); i++) {
            aux = Main.Storage.Usuarios.get(i);
            Mat [i][0]= Integer.toString(aux.getIdUsuario());
            Mat [i][1]= aux.getNombre();
            Mat [i][2]= aux.getApellidoP();
            Mat [i][3]= aux.getApellidoM();
            Mat [i][4]= aux.getDireccion();
            if (aux.getUserType() == 0) {
               Mat [i][5]= "Estudiante"; 
            }else if(aux.getUserType() == 1){
               Mat [i][5]= "Cliente";
            }
            
            
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Mat,           
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Dirección", "Tipo"
            }
        ));
    }    private void mostrarUsuarios(Usuario aux) {
        String Mat[] [] = new String[1][5];
            Mat [1][0]= Integer.toString(aux.getIdUsuario());
            Mat [1][1]= aux.getNombre();
            Mat [1][2]= aux.getApellidoP();
            Mat [1][3]= aux.getApellidoM();
            Mat [1][4]= aux.getDireccion();
            Mat [1][5]= Integer.toString(aux.getUserType());
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Mat,           
            new String [] {
               "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Dirección", "Tipo"
            }
        ));
    }

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        int c;
        try {
            c= jTable1.getSelectedRow();
            Main.Storage.Usuarios.remove(c);                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Escoje una fila para eliminar");
        }
        cargarDatos();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
           int c;
        String nombre,ApeP,ApeM,Dir;
        Usuario aux;
        try {
            c = jTable1.getSelectedRow();
            aux = Main.Storage.Usuarios.get(c);
            nombre = JOptionPane.showInputDialog("Nuevo nombre");
            aux.setNombre(nombre);
            aux = Main.Storage.Usuarios.get(c);
            ApeP = JOptionPane.showInputDialog("Nuevo Apellido Paterno");
            aux.setApellidoP(ApeP);
            aux = Main.Storage.Usuarios.get(c);
            ApeM = JOptionPane.showInputDialog("Nuevo Apellido Materno");
            aux.setApellidoM(ApeM);
            aux = Main.Storage.Usuarios.get(c);
            Dir = JOptionPane.showInputDialog("Nueva Dirección");
            aux.setDireccion(Dir);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "escojer una fila");
        }
        cargarDatos();
    }//GEN-LAST:event_jPanel2MousePressed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
